Repository movesthatmatter/movex, pull requests merged in 2023-10, with the labels that each got.

#35 renamed to applyMovexStatePatches
  libs/movex/src/lib/util.ts
Labels: good first issue, hacktoberfest

#34 removed commented code
  libs/movex/README.md
  libs/movex/src/lib/client/Movex.ts
Labels: good first issue, hacktoberfest

#36 imported the md5 function instead of the whole object-hash
  libs/movex/src/lib/util.ts
Labels: good first issue, hacktoberfest

#49 removed method getReducerApplicator
  libs/movex/src/lib/tools/dispatch.ts
Labels: good first issue, hacktoberfest

#53 Removed self referencing absolute imports [libs/movex-react]
  libs/movex-react/src/lib/MovexBoundResource.tsx
  libs/movex-react/src/lib/MovexContextStateChange.tsx
  libs/movex-react/src/lib/MovexResourceBounder.tsx
Labels: good first issue, hacktoberfest

#57 refactor: :recycle: fix_Self_Refencing_Absolute_Imports
  libs/movex/src/lib/client/init.ts
  libs/movex/src/specs/resources/rockPaperScissors.movex.ts
Labels: good first issue, hacktoberfest

#33 clean up CoreTypes file of commented code
  libs/movex-core-util/src/lib/core-types.ts
Labels: good first issue, hacktoberfest

#50 Clean ups
  libs/movex-react/src/lib/hooks.ts
Labels: good first issue, hacktoberfest

#76 Cleaned up HeroText
  apps/movex-docs/modules/home/Hero.tsx
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#65 refactor: removal of `initMovexWithLocalMaster` function and related unused dependencies
  libs/movex/src/lib/client/init.ts
Labels: good first issue, hacktoberfest

#80 refactor: 💡 Implement IObservable for Observable
  libs/movex-core-util/src/lib/core-util/Observable.ts
  libs/movex/src/lib/client/MovexResourceObservable.ts
  libs/movex/src/specs/MovexClientResourceObservable.spec.ts
Labels: good first issue, hacktoberfest

#86 Removed commented code from MovexResourceObservable.
  libs/movex/src/lib/client/MovexResourceObservable.ts
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#91 Turn off verbose logging
  libs/movex-core-util/src/lib/core-util/Logsy.ts
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#145 Removed unused interface
  libs/movex-core-util/src/lib/core-util/EventEmitter.ts
Labels: good first issue, feature request

#155 Fix "[project] Rename the Github Action: node.js.yml #150" and "[project] Remove the node-18.x from CI Github Action #149"
  .github/workflows/test.yml
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#159 Add "[Project] Add command to serve movex-docs #158"
  package.json
Labels: hacktoberfest

#176 Fix "[libs/movex] Fix linting Errors in File ClientMaster.rps.spec.ts…
  libs/movex/src/specs/ClientMasterOrchestration/ClientMaster.rps.spec.ts
  libs/movex/src/specs/ClientMasterOrchestration/console-group.d.ts
Labels: good first issue, hacktoberfest

#174 fix(lint): memory-movex-store-spec
  libs/movex/src/lib/movex-store/MemoryMovexStore.spec.ts
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#182 Fixed linting in 'io-events.ts'
  libs/movex/src/lib/io-connection/io-events.ts
Labels: good first issue, hacktoberfest, hacktoberfest-accepted
